# CMake generated Testfile for 
# Source directory: /Users/vincent/git/github.com/vincentk/dedekind
# Build directory: /Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_category]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_category")
set_tests_properties([=[test_category]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-category-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;173;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_ieee]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_ieee")
set_tests_properties([=[test_ieee]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-ieee-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;174;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_sets]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_sets")
set_tests_properties([=[test_sets]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-sets-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;175;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_order]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_order")
set_tests_properties([=[test_order]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-order-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;176;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_topology]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_topology")
set_tests_properties([=[test_topology]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-topology-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;177;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_sequences]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_sequences")
set_tests_properties([=[test_sequences]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-sequences-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;178;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_algebra]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_algebra")
set_tests_properties([=[test_algebra]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-algebra-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;179;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_morphologies]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_morphologies")
set_tests_properties([=[test_morphologies]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-morphologies-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;180;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_geometry]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_geometry")
set_tests_properties([=[test_geometry]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-geometry-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;181;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_numbers]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_numbers")
set_tests_properties([=[test_numbers]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-numbers-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;182;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_analysis]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_analysis")
set_tests_properties([=[test_analysis]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-analysis-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;183;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_python]=] "/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/test_python")
set_tests_properties([=[test_python]=] PROPERTIES  ENVIRONMENT "LLVM_PROFILE_FILE=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/dedekind-python-%m.profraw" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;149;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;184;add_dedekind_layer;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
add_test([=[test_python_bindings]=] "/Users/vincent/git/github.com/vincentk/dedekind/.venv/bin/python" "-m" "unittest" "discover" "-s" "/Users/vincent/git/github.com/vincentk/dedekind/src/test/python" "-p" "test_*.py")
set_tests_properties([=[test_python_bindings]=] PROPERTIES  ENVIRONMENT "PYTHONPATH=/Users/vincent/git/github.com/vincentk/dedekind/build-python/cp313-cp313-macosx_15_0_x86_64/python" _BACKTRACE_TRIPLES "/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;211;add_test;/Users/vincent/git/github.com/vincentk/dedekind/CMakeLists.txt;0;")
subdirs("_deps/catch2-build")
subdirs("ext/nanobind")
