import math
PI=math.pi
def om(E,th):
    v=2*(E+math.cos(th)); return math.sqrt(v) if v>1e-9 else 0.0
def libration(E,N=180):          # closed orbit inside the separatrix
    thm=math.acos(max(-1.0,min(1.0,-E)))
    up=[(-thm+2*thm*i/N, om(E,-thm+2*thm*i/N)) for i in range(N+1)]
    return up+[(t,-w) for t,w in reversed(up)]+[up[0]]
def rotation(E,sgn,N=200):       # over-the-top, ω keeps its sign
    return [(-PI+2*PI*i/N, sgn*om(E,-PI+2*PI*i/N)) for i in range(N+1)]
def sep(sgn,N=200):              # separatrix, E=1: ω=±2|cos(θ/2)|
    return [(-PI+2*PI*i/N, sgn*2*abs(math.cos((-PI+2*PI*i/N)/2))) for i in range(N+1)]

o=[r"% GENERATED by pendulum.py", r"\begin{tikzpicture}[x=1.05cm,y=0.62cm,>=Stealth,font=\small]"]
def path(pts,st):
    o.append(r"\draw[%s] plot coordinates{%s};"%(st," ".join("(%.3f,%.3f)"%p for p in pts)))
for E in (-0.7,-0.3,0.2,0.7):    path(libration(E),"blue!55,thick")
for E in (1.25,1.7,2.2):
    path(rotation(E,+1),"teal!55!black,thick"); path(rotation(E,-1),"teal!55!black,thick")
path(sep(+1),"orange!88!black,very thick"); path(sep(-1),"orange!88!black,very thick")
o.append(r"\node[orange!80!black,font=\scriptsize] at (1.7,1.75){separatrix};")
o.append(r"\draw[->,gray!70] (-3.7,0)--(3.8,0) node[right]{$\theta$};")
o.append(r"\draw[->,gray!70] (0,-3.3)--(0,3.4) node[above]{$\omega$};")
o.append(r"\draw[gray!45,dashed] (-3.1416,-3.1)--(-3.1416,3.1) (3.1416,-3.1)--(3.1416,3.1);")
o.append(r"\node[gray,font=\scriptsize] at (3.1416,-0.45){$\pi$}; \node[gray,font=\scriptsize] at (-3.1416,-0.45){$-\pi$};")
# fixed points: centre at (0,0), saddles at (±π,0)
o.append(r"\fill[black] (0,0) circle(2.4pt);")
o.append(r"\node[font=\scriptsize,anchor=north east] at (-0.1,-0.2){centre (at rest)};")
def X(cx,cy,rx=0.16,ry=0.26):
    o.append(r"\draw[black,very thick] (%.3f,%.3f)--(%.3f,%.3f) (%.3f,%.3f)--(%.3f,%.3f);"%(cx-rx,cy-ry,cx+rx,cy+ry,cx-rx,cy+ry,cx+rx,cy-ry))
X(PI,0); X(-PI,0)
o.append(r"\node[font=\scriptsize,anchor=south] at (3.1416,0.35){saddle (inverted)};")
o.append(r"\end{tikzpicture}")
open("hsp_pendulum.tex","w").write("\n".join(o)); print("ok",len(o))
