; Placeholder LLVM IR for pruning_noop_vs_runtime_fixture
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; @pruning_compile_time_noop - Compile-time pruned path
; Expected: single `ret i1 false` due to constant folding

; @pruning_runtime_guard - Runtime path with function pointer
; Expected: indirect call through the function pointer

; @impress_empty_diagonal_cut - Contradiction on diagonal in R^2
; Expected: compile-time constant false

; @impress_lattice_square_singleton - Lattice/square singleton witness
; Expected: compile-time constant true

attributes #0 = { noinline uwtable }
