; Placeholder LLVM IR for pruning_noop_vs_runtime_fixture
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.

; @pruning_compile_time_noop - Compile-time pruned path
; Expected: single `ret i1 false` due to constant folding

; @pruning_runtime_guard - Runtime path with function pointer
; Expected: indirect call through the function pointer

; @impress_empty_diagonal_cut - Contradiction on diagonal in R^2
; Expected: compile-time constant false

; @impress_lattice_square_singleton - Lattice/square singleton witness
; Expected: compile-time constant true

attributes #0 = { noinline uwtable }
