; Placeholder LLVM IR for showcase_02_lattice_singleton
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; @impress_lattice_square_singleton - Lattice/square singleton witness
; Expected: compile-time constant `ret i1 true`

attributes #0 = { noinline uwtable }
