; Placeholder LLVM IR for showcase_01_diagonal_contradiction
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.

; @impress_empty_diagonal_cut - Contradiction on diagonal in R^2
; Expected: compile-time constant `ret i1 false`

attributes #0 = { noinline uwtable }
