; Placeholder LLVM IR for showcase_02_lattice_singleton
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.

; @impress_lattice_square_singleton - Lattice/square singleton witness
; Expected: compile-time constant `ret i1 true`

attributes #0 = { noinline uwtable }
