; Placeholder LLVM IR for showcase_01_diagonal_contradiction
; This file is regenerated by .github/copilot/housekeeping/pruning-ir-fixture.py
; Do not edit manually.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; @impress_empty_diagonal_cut - Contradiction on diagonal in R^2
; Expected: compile-time constant `ret i1 false`

attributes #0 = { noinline uwtable }
